---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kerberos-init
  namespace: pnfs-test

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kerberos-init-role
  namespace: pnfs-test
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "patch", "get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kerberos-init-rolebinding
  namespace: pnfs-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kerberos-init-role
subjects:
- kind: ServiceAccount
  name: kerberos-init
  namespace: pnfs-test
