apiVersion: v1
kind: Service
metadata:
  name: pnfs-ds-1
  namespace: pnfs-test
  labels:
    app: pnfs-ds
    ds-id: "1"
spec:
  selector:
    app: pnfs-ds
    statefulset.kubernetes.io/pod-name: pnfs-ds-0
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pnfs-ds-2
  namespace: pnfs-test
  labels:
    app: pnfs-ds
    ds-id: "2"
spec:
  selector:
    app: pnfs-ds
    statefulset.kubernetes.io/pod-name: pnfs-ds-1
  ports:
  - name: nfs
    port: 2049
    targetPort: 2049
    protocol: TCP
  type: ClusterIP

