# This YAML file defines the Flint CSI sidecar controllers.
---
# The Deployment for the external-provisioner.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flint-csi-provisioner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flint-csi-provisioner
  template:
    metadata:
      labels:
        app: flint-csi-provisioner
    spec:
      serviceAccountName: flint-csi-controller
      containers:
        - name: csi-provisioner
          image: "{{ .Values.csiSidecars.repository }}/{{ .Values.csiSidecars.externalProvisioner.name }}:{{ .Values.csiSidecars.externalProvisioner.tag }}"
          imagePullPolicy: Always
          args:
            - "--csi-address=/csi/csi.sock"
            - "--feature-gates=Topology=true"
            - "--v=5"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
# The Deployment for the external-attacher.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flint-csi-attacher
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flint-csi-attacher
  template:
    metadata:
      labels:
        app: flint-csi-attacher
    spec:
      serviceAccountName: flint-csi-controller
      containers:
        - name: csi-attacher
          image: "{{ .Values.csiSidecars.repository }}/{{ .Values.csiSidecars.externalAttacher.name }}:{{ .Values.csiSidecars.externalAttacher.tag }}"
          imagePullPolicy: Always
          args:
            - "--csi-address=/csi/csi.sock"
            - "--v=5"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
# The Deployment for the external-resizer.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flint-csi-resizer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flint-csi-resizer
  template:
    metadata:
      labels:
        app: flint-csi-resizer
    spec:
      serviceAccountName: flint-csi-controller
      containers:
        - name: csi-resizer
          image: "{{ .Values.csiSidecars.repository }}/{{ .Values.csiSidecars.externalResizer.name }}:{{ .Values.csiSidecars.externalResizer.tag }}"
          imagePullPolicy: Always
          args:
            - "--csi-address=/csi/csi.sock"
            - "--v=5"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
---
# The Deployment for the external-snapshotter.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flint-csi-snapshotter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flint-csi-snapshotter
  template:
    metadata:
      labels:
        app: flint-csi-snapshotter
    spec:
      serviceAccountName: flint-csi-controller
      containers:
        - name: csi-snapshotter
          image: "{{ .Values.csiSidecars.repository }}/{{ .Values.csiSidecars.externalSnapshotter.name }}:{{ .Values.csiSidecars.externalSnapshotter.tag }}"
          imagePullPolicy: Always
          args:
            - "--csi-address=/csi/csi.sock"
            - "--v=5"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
