{{- if .Values.rbac.create -}}
---
{{- if .Values.serviceAccount.controller.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flint-csi-driver-chart.serviceAccountName.controller" . }}
  labels:
    {{- include "flint-csi-driver-chart.labels" . | nindent 4 }}
{{- end -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "flint-csi-driver-chart.fullname" . }}-controller-role
  labels:
    {{- include "flint-csi-driver-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "flint-csi-driver-chart.fullname" . }}-controller-binding
  labels:
    {{- include "flint-csi-driver-chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "flint-csi-driver-chart.serviceAccountName.controller" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "flint-csi-driver-chart.fullname" . }}-controller-role
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.serviceAccount.node.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flint-csi-driver-chart.serviceAccountName.node" . }}
  labels:
    {{- include "flint-csi-driver-chart.labels" . | nindent 4 }}
{{- end -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "flint-csi-driver-chart.fullname" . }}-node-role
  labels:
    {{- include "flint-csi-driver-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "flint-csi-driver-chart.fullname" . }}-node-binding
  labels:
    {{- include "flint-csi-driver-chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "flint-csi-driver-chart.serviceAccountName.node" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "flint-csi-driver-chart.fullname" . }}-node-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
