# This YAML file defines all the RBAC resources for the Flint CSI driver.

# Service account for the controller components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flint-csi-controller
  namespace: {{ .Release.Namespace }}

---

# ClusterRole for the controller components
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flint-csi-controller
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["patch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes", "volumeattachments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses", "volumesnapshotcontents"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: ["flint.csi.storage.io"]
    resources: ["spdkvolumes", "spdkdisks", "spdksnapshots"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["flint.csi.storage.io"]
    resources: ["spdkvolumes/status", "spdkdisks/status", "spdksnapshots/status"]
    verbs: ["get", "update", "patch"]

---

# ClusterRoleBinding for the controller components
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flint-csi-controller
subjects:
  - kind: ServiceAccount
    name: flint-csi-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: flint-csi-controller
  apiGroup: rbac.authorization.k8s.io

---

# Service account for the node components
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flint-csi-node
  namespace: {{ .Release.Namespace }}

---
# ClusterRole for the node components
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flint-csi-node
rules:
  - apiGroups: [""]
    resources: ["configmaps", "nodes", "pods", "events"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["flint.csi.storage.io"]
    resources: ["spdkdisks", "spdkvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["flint.csi.storage.io"]
    resources: ["spdkdisks/status", "spdkvolumes/status"]
    verbs: ["get", "update", "patch"]
---

# ClusterRoleBinding for the node components
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flint-csi-node
subjects:
  - kind: ServiceAccount
    name: flint-csi-node
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: flint-csi-node
  apiGroup: rbac.authorization.k8s.io
