{{- if .Values.snapshotClass.enabled }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.snapshotClass.name }}
  labels:
    {{- include "flint-csi-driver-chart.labels" . | nindent 4 }}
driver: {{ .Values.driver.name }}
deletionPolicy: {{ .Values.snapshotClass.deletionPolicy }}
{{- if .Values.snapshotClass.parameters }}
parameters:
  {{- toYaml .Values.snapshotClass.parameters | nindent 2 }}
{{- end }}
{{- end }}

