#!/bin/bash
# ---------------------------------------------------------------------------
# Regenerate (or verify) the render-parity fixture the flint-lite operator's
# golden test compares against.
#
#   scripts/check-render-parity.sh          # verify: fails if stale
#   scripts/check-render-parity.sh --write  # regenerate from the chart
#
# WHY A FIXTURE AND NOT `helm template` FROM THE TEST
#
# The lib suite's real home is a lima Linux VM (the macOS suite is not the
# suite), and there is no helm in it. A test that skips when its tool is
# missing is a test that passes by not looking — this project has been
# bitten by that class more than once. So helm runs HERE, at authoring
# time, and the test compares against the recorded output.
#
# Staleness is the obvious failure of that trade, and it is closed from the
# other side: the fixture records a sha256 over every chart file that can
# change a render, and the Rust test recomputes it (render::chart_sha256).
# Edit the chart without re-running this script and the SUITE fails, not
# some future cluster.
#
# The case definitions (`values` for helm, `spec` for the operator) are
# authored by hand IN the fixture; this script only fills in what helm
# renders. Adding a case = adding an entry there, then --write.
# ---------------------------------------------------------------------------
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
repo_root=$(cd "$here/.." && pwd)
chart_dir="$repo_root/flint-lite-chart"
fixture="$repo_root/spdk-csi-driver/tests/fixtures/lite-chart-render.json"

mode=${1:---check}
case "$mode" in --check|--write) ;; *)
    echo "usage: $0 [--check|--write]" >&2; exit 2 ;;
esac

command -v helm >/dev/null || { echo "helm not found — this script needs it" >&2; exit 2; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

python3 - "$chart_dir" "$fixture" "$tmp" "$mode" <<'PYEOF'
import hashlib, json, subprocess, sys, os
import yaml

chart_dir, fixture, tmp, mode = sys.argv[1:5]

# Same inputs, same order, as render::chart_sha256() — if you change one,
# change both (the test compares the two hashes).
h = hashlib.sha256()
for rel in ("Chart.yaml", "values.yaml", "templates/hub.yaml", "templates/_helpers.tpl"):
    with open(os.path.join(chart_dir, rel), "rb") as f:
        h.update(f.read())
chart_sha = h.hexdigest()

doc = json.load(open(fixture))
cases = doc["cases"]

for name, case in cases.items():
    vf = os.path.join(tmp, f"{name}.yaml")
    with open(vf, "w") as f:
        f.write(case["values"])
    # Release name `flint-lite` on purpose: the chart's object names are
    # fixed, and they are exactly the names the operator derives for a
    # share called flint-lite. That makes the comparison like-for-like
    # instead of a normalization exercise.
    out = subprocess.run(
        ["helm", "template", "flint-lite", chart_dir, "-n", "flint", "-f", vf],
        check=True, capture_output=True, text=True).stdout
    objs = [d for d in yaml.safe_load_all(out) if d]
    by_kind = {}
    for o in objs:
        by_kind.setdefault(o["kind"], []).append(o)
    for kind, n in (("ConfigMap", 1), ("PersistentVolumeClaim", 1), ("Service", 1), ("Deployment", 1)):
        got = len(by_kind.get(kind, []))
        if got != n:
            sys.exit(f"case {name}: expected {n} {kind}, chart rendered {got}")

    case["mdsYaml"] = by_kind["ConfigMap"][0]["data"]["mds.yaml"]
    case["deployment"] = by_kind["Deployment"][0]
    case["service"] = by_kind["Service"][0]
    case["pvc"] = by_kind["PersistentVolumeClaim"][0]

doc["chartSha256"] = chart_sha
doc["_note"] = ("GENERATED by scripts/check-render-parity.sh from flint-lite-chart. "
                "`values` and `spec` are hand-authored case definitions; every other "
                "field is helm's output. Do not hand-edit the rendered halves.")

new = json.dumps(doc, indent=2, sort_keys=True) + "\n"
old = open(fixture).read() if os.path.exists(fixture) else ""

if mode == "--write":
    open(fixture, "w").write(new)
    print(f"wrote {fixture} ({len(cases)} cases, chart {chart_sha[:12]})")
elif new != old:
    sys.exit("render-parity fixture is STALE — flint-lite-chart changed since it was "
             "generated. Re-run: scripts/check-render-parity.sh --write "
             "(and re-read the diff: a chart change the operator does not make is a "
             "real divergence, not a formality).")
else:
    print(f"render-parity fixture current ({len(cases)} cases, chart {chart_sha[:12]})")
PYEOF
