// Minimal State SPDK CSI Driver - Library Modules

// The dashboard's warp route chain (spdk_dashboard_backend_minimal) nests one
// filter type per `.or(route)`; at 20+ routes the trait solver overflows the
// default limit of 128 on rustc <=1.92 (E0275 at the /api/nodes addition).
#![recursion_limit = "256"]

pub mod identity;  // Canonical volume identity: VolumeRef + naming + parsers (identity-unification Phase 0)
pub mod spdk_native;
pub mod nvmeof_utils;
pub mod nvmeof_export;  // Convergent NVMe-oF export (phase 0 idempotency fix)
pub mod nvme_recovery;  // Graceful recovery from spdk-tgt hard stop/restart (#1 reconcile-on-loss, #2 survivable reconnect, #3 disconnect-before-reuse)
pub mod replica_sync;  // Persistent per-replica sync state on the PV (incremental-rebuild phase 1)
pub mod epoch_scheduler;  // Common-epoch snapshot scheduler (incremental-rebuild phase 2)
pub mod catchup;  // Replica catch-up orchestrator / warm standby + reassembly admission (incremental-rebuild phases 3/4)
pub mod replica_replace;  // U11: replica re-placement after permanent node loss (pre-pass of the catch-up task)
pub mod cutover;  // Reassembly cutover: RWX NFS-pod bounce + RWO policy knob (incremental-rebuild phase 4)
pub mod driver;
pub mod minimal_models;
pub mod minimal_disk_service;
pub mod node_agent;
pub mod mount_util;  // Bounded unmount (D-state hang containment, 2026-06-12)
pub mod ublk_ctrl;  // UBLK_U_CMD_DEL_DEV escape hatch (DEAD-device reclaim, runy2 2026-07-21)
pub mod orphan_sweep;  // §10-14 node-local reaping of lvols/exports keyed by absent PVs
pub mod controller_reap;  // Dead NVMe-oF controller reaping (Tier-2 7b-0 spike finding)
pub mod hot_rejoin;  // Tier-2 7b-1/7b-2: hot rejoin into a live raid (skip_rebuild window + localization + trigger loop)
pub mod volume_claims;  // Tier-2 7b-2: per-volume single-operation claim shared by catch-up/cutover/hot-rejoin
pub mod freshness_gate;  // F36c: last-writer-set degraded-assembly gate (docs/f36c-assembly-freshness-gate.md)
pub mod guarded_destroy;  // Contract R3: the destruction chokepoint (docs/attach-detach-robustness-contract.md)
pub mod node_volume_locks;  // Contract R2: per-volume node-local lock (probe→mutate serialization; kill switch FLINT_VOLUME_LOCK)
pub mod spdk_dashboard_backend_minimal;
pub mod dashboard_auth;  // Bearer-token auth for the dashboard backend (frontend Phase 0)
pub mod snapshot;  // Volume snapshot support (isolated module)
pub mod capacity_cache;  // Capacity caching for scalability
pub mod raid;  // RAID support for multi-replica volumes
pub mod nfs;  // NFSv4.2 server for RWX volume support
pub mod rwx_nfs;  // ReadWriteMany (RWX) support via NFS pods (isolated module - zero regression)
pub mod pnfs;  // pNFS (Parallel NFS) support - metadata/data server separation (experimental)
pub mod pnfs_csi;  // CSI driver-side client to the pNFS MDS (used by main.rs when layout: pnfs)
pub mod reserved_devices;  // Device reservation for direct SPDK access (device plugin use)
pub mod state_backend;  // Persistence trait + impls for NFSv4/pNFS server state (Phase B)

// Include generated CSI protobuf types (generated by tonic-build)
pub mod csi {
    #![allow(non_camel_case_types)]
    #![allow(clippy::all)]
    // tonic-build generates files based on package name: csi.v1 -> csi.v1.rs
    include!(concat!(env!("OUT_DIR"), "/csi.v1.rs"));
}

// Export minimal models instead of CRD models
pub use minimal_models::*;

/// CSI topology segment key advertised by every node (NodeGetInfo) and
/// consumed by the controller's single-replica placement. The segment
/// value is the k8s node name (== NODE_ID == the names get_all_nodes()
/// returns), so a `preferred` topology from a WaitForFirstConsumer bind
/// names the node the consuming pod scheduled onto. Placement honors it
/// so a single-replica volume's lvol lands on the same node as its pod
/// (data locality; and it lets anti-affinity-spread pods — e.g. sharded
/// MDS shards — pull their state.db disks onto distinct nodes). Absent /
/// unparseable topology degrades to the historical max-free placement.
pub const TOPOLOGY_NODE_KEY: &str = "topology.flint.csi.storage.io/node";

/// Extract the ordered list of preferred node names from a CreateVolume
/// request's `accessibility_requirements`. Reads the [`TOPOLOGY_NODE_KEY`]
/// segment out of each `preferred` topology, preserving the CO's order
/// (the CO lists the selected node first for WaitForFirstConsumer binds).
/// Returns empty when there is no requirement or no recognizable segment —
/// which the placement path treats as "no hint, use max-free".
pub fn preferred_nodes_from_topology(
    accessibility: Option<&csi::TopologyRequirement>,
) -> Vec<String> {
    accessibility
        .map(|tr| {
            tr.preferred
                .iter()
                .filter_map(|t| t.segments.get(TOPOLOGY_NODE_KEY).cloned())
                .collect()
        })
        .unwrap_or_default()
}

#[cfg(test)]
mod topology_tests {
    use super::*;
    use csi::{Topology, TopologyRequirement};
    use std::collections::HashMap;

    fn topo(node: &str) -> Topology {
        let mut segments = HashMap::new();
        segments.insert(TOPOLOGY_NODE_KEY.to_string(), node.to_string());
        Topology { segments }
    }

    #[test]
    fn none_requirement_yields_empty() {
        assert!(preferred_nodes_from_topology(None).is_empty());
    }

    #[test]
    fn reads_preferred_in_order() {
        let req = TopologyRequirement {
            requisite: vec![topo("node-a"), topo("node-b")],
            preferred: vec![topo("node-b"), topo("node-a")],
        };
        assert_eq!(
            preferred_nodes_from_topology(Some(&req)),
            vec!["node-b".to_string(), "node-a".to_string()]
        );
    }

    #[test]
    fn ignores_foreign_segment_keys() {
        let mut segments = HashMap::new();
        segments.insert("topology.kubernetes.io/zone".to_string(), "us-west-1a".to_string());
        let req = TopologyRequirement {
            requisite: vec![],
            preferred: vec![Topology { segments }],
        };
        assert!(preferred_nodes_from_topology(Some(&req)).is_empty());
    }
}
