// Minimal State SPDK CSI Driver - Library Modules
pub mod spdk_native;
pub mod nvmeof_utils;
pub mod nvmeof_export;  // Convergent NVMe-oF export (phase 0 idempotency fix)
pub mod replica_sync;  // Persistent per-replica sync state on the PV (incremental-rebuild phase 1)
pub mod epoch_scheduler;  // Common-epoch snapshot scheduler (incremental-rebuild phase 2)
pub mod catchup;  // Replica catch-up orchestrator / warm standby + reassembly admission (incremental-rebuild phases 3/4)
pub mod cutover;  // Reassembly cutover: RWX NFS-pod bounce + RWO policy knob (incremental-rebuild phase 4)
pub mod driver;
pub mod minimal_models;
pub mod minimal_disk_service;
pub mod node_agent;
pub mod mount_util;  // Bounded unmount (D-state hang containment, 2026-06-12)
pub mod orphan_sweep;  // §10-14 node-local reaping of lvols/exports keyed by absent PVs
pub mod spdk_dashboard_backend_minimal;
pub mod snapshot;  // Volume snapshot support (isolated module)
pub mod capacity_cache;  // Capacity caching for scalability
pub mod raid;  // RAID support for multi-replica volumes
pub mod nfs;  // NFSv4.2 server for RWX volume support
pub mod rwx_nfs;  // ReadWriteMany (RWX) support via NFS pods (isolated module - zero regression)
pub mod pnfs;  // pNFS (Parallel NFS) support - metadata/data server separation (experimental)
pub mod pnfs_csi;  // CSI driver-side client to the pNFS MDS (used by main.rs when layout: pnfs)
pub mod reserved_devices;  // Device reservation for direct SPDK access (device plugin use)
pub mod state_backend;  // Persistence trait + impls for NFSv4/pNFS server state (Phase B)

// Include generated CSI protobuf types (generated by tonic-build)
pub mod csi {
    #![allow(non_camel_case_types)]
    #![allow(clippy::all)]
    // tonic-build generates files based on package name: csi.v1 -> csi.v1.rs
    include!(concat!(env!("OUT_DIR"), "/csi.v1.rs"));
}

// Export minimal models instead of CRD models
pub use minimal_models::*;
