// snapshot.rs
use kube::CustomResource;
use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

/// Defines the type of the snapshot to distinguish between snapshots, clones, etc.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub enum SnapshotType {
    /// A standard, read-only point-in-time snapshot of a bdev.
    #[default]
    Bdev,
    /// A writable volume created from a snapshot (clone).
    LvolClone,
    /// A snapshot originating from an external or imported source.
    External,
}


#[derive(CustomResource, Serialize, Deserialize, Debug, Clone, Default)]
#[kube(
    group = "csi.spdk.io",
    version = "v1",
    kind = "SpdkSnapshot",
    plural = "spdksnapshots"
)]
#[kube(namespaced)]
#[kube(status = "SpdkSnapshotStatus")]
#[kube(printcolumn = r#"{"name":"Source Volume", "type":"string", "jsonPath":".spec.source_volume_id"}"#)]
#[kube(printcolumn = r#"{"name":"Type", "type":"string", "jsonPath":".spec.snapshot_type"}"#)]
#[kube(printcolumn = r#"{"name":"Ready", "type":"boolean", "jsonPath":".status.ready_to_use"}"#)]
#[kube(printcolumn = r#"{"name":"Size", "type":"string", "jsonPath":".status.size_bytes"}"#)]
#[kube(printcolumn = r#"{"name":"Created At", "type":"date", "jsonPath":".status.creation_time"}"#)]
pub struct SpdkSnapshotSpec {
    /// The volume_id of the SpdkVolume this is a snapshot of.
    pub source_volume_id: String,
    /// The unique ID for this snapshot, as generated by the CSI sidecar.
    pub snapshot_id: String,
    /// The name of the underlying snapshot lvol in SPDK.
    pub spdk_snapshot_lvol: String,
    /// The type of snapshot, indicating if it's a standard snapshot, clone, etc.
    #[serde(default)]
    pub snapshot_type: SnapshotType,
    /// If the snapshot represents a clone, this specifies the source snapshot ID.
    pub clone_source_snapshot_id: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct SpdkSnapshotStatus {
    /// Timestamp when the snapshot was created.
    pub creation_time: Option<DateTime<Utc>>,
    /// Indicates if the snapshot is ready for use.
    pub ready_to_use: bool,
    /// The size of the source volume at the time of snapshot.
    pub size_bytes: i64,
    /// Any error message if the snapshot creation failed.
    pub error: Option<String>,
}
