/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["disks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["nodes_projection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node}/disks/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["node_disks_delete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node}/disks/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["node_disks_initialize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node}/disks/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["node_disks_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node}/disks/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["node_disks_setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node}/disks/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["node_disk_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{node}/disks/uninitialized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["node_disks_uninitialized"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["snapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["snapshots_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["volumes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/volumesnapshots/{namespace}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["volumesnapshot_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            error: string;
        };
        /**
         * @description Tier-2 data plane (2b): each consumer node that stages the volume
         *     assembles `raid_<pv>` locally from the replica legs — one row per
         *     consumer. Presence of the raid bdev on a node IS the consumer set;
         *     no VolumeAttachment inference.
         */
        ConsumerRaid: {
            base_bdevs: components["schemas"]["ConsumerRaidMember"][];
            node: string;
            /** Format: int32 */
            num_base_bdevs: number;
            /** Format: int32 */
            num_base_bdevs_operational: number;
            raid_name: string;
            /**
             * @description SPDK raid state (online/configuring/offline). "online" with
             *     operational < total is the degraded-n/m case.
             */
            state: string;
        };
        ConsumerRaidMember: {
            is_configured: boolean;
            /**
             * @description SPDK nulls name+uuid when a leg fails on an online raid
             *     (raid_bdev_free_base_bdev_resource) — a null member IS a failed slot.
             */
            name?: string | null;
            /**
             * @description Replica (by node) this base backs, resolved against the sync record;
             *     None when unmatchable (failed slot, no record).
             */
            replica_node?: string | null;
            uuid?: string | null;
        };
        DashboardData: {
            disks: components["schemas"]["DashboardDisk"][];
            node_info: {
                [key: string]: components["schemas"]["NodeInfo"];
            };
            nodes: string[];
            raw_volumes: Record<string, never>[];
            volumes: components["schemas"]["DashboardVolume"][];
        };
        DashboardDisk: {
            /** Format: double */
            allocated_space: number;
            blobstore_initialized: boolean;
            brought_online: string;
            /** Format: int64 */
            capacity: number;
            /** Format: double */
            capacity_gb: number;
            device_type: string;
            /** Format: double */
            free_space: number;
            free_space_display: string;
            healthy: boolean;
            id: string;
            is_system_disk: boolean;
            /** Format: int32 */
            lvol_count: number;
            model: string;
            node: string;
            orphaned_spdk_volumes: components["schemas"]["OrphanedVolumeInfo"][];
            pci_addr: string;
            provisioned_volumes: components["schemas"]["ProvisionedVolume"][];
            /** Format: int64 */
            read_iops: number;
            /** Format: int64 */
            read_latency: number;
            /** Format: int64 */
            write_iops: number;
            /** Format: int64 */
            write_latency: number;
        };
        /** @description A flint engine event projected for the dashboard timeline (2c). */
        DashboardEvent: {
            category: string;
            event_type: string;
            message: string;
            reason: string;
            reporting_instance: string;
            timestamp?: string | null;
            volume: string;
        };
        DashboardOverview: {
            degraded_volumes: number;
            failed_volumes: number;
            faulted_volumes: number;
            healthy_disks: number;
            healthy_volumes: number;
            initialized_disks: number;
            local_nvme_volumes: number;
            total_disks: number;
            total_nodes: number;
            total_volumes: number;
        };
        DashboardRaidStatus: {
            auto_rebuild_enabled: boolean;
            /** Format: int32 */
            discovered_members: number;
            members: components["schemas"]["RaidMember"][];
            /** Format: int32 */
            num_members: number;
            /** Format: int32 */
            operational_members: number;
            /** Format: int32 */
            raid_level: number;
            rebuild_info?: null | components["schemas"]["RebuildInfo"];
            state: string;
            /** Format: int32 */
            superblock_version?: number | null;
        };
        DashboardReplicaStatus: {
            access_method: string;
            is_local: boolean;
            is_new_replica?: boolean | null;
            last_io_timestamp?: string | null;
            node: string;
            nvmf_target?: null | components["schemas"]["NvmfTarget"];
            /** Format: int32 */
            raid_member_slot?: number | null;
            raid_member_state: string;
            /** Format: double */
            rebuild_progress?: number | null;
            rebuild_target?: string | null;
            status: string;
            sync?: null | components["schemas"]["ReplicaSyncInfo"];
        };
        /**
         * @description One logical snapshot: the per-node SPDK copies merged by snapshot name.
         *     Copies of the same snapshot share the name; each node's copy is its own
         *     lvol with its own uuid.
         */
        DashboardSnapshot: {
            /**
             * @description Node-agent list stamp, not a real creation time (SPDK lvols store
             *     none) — real times are the timeline endpoint's job.
             */
            creation_time: string;
            lvs_name?: string | null;
            /** @description Node of the first copy; the copy list is authoritative. */
            node: string;
            ready_to_use: boolean;
            /** @description One entry per node currently holding a copy. */
            replica_bdev_details: components["schemas"]["SnapshotCopy"][];
            /** Format: int64 */
            size_bytes: number;
            snapshot_name: string;
            /**
             * @description UUID of the first copy (nodes sorted) — a stable display id, not
             *     shared by the other copies.
             */
            snapshot_uuid: string;
            source_volume_id: string;
        };
        DashboardVolume: {
            access_method: string;
            /** Format: int32 */
            active_replicas: number;
            consumer_raids: components["schemas"]["ConsumerRaid"][];
            current_epoch?: string | null;
            id: string;
            local_nvme: boolean;
            name: string;
            nodes: string[];
            nvmeof_enabled: boolean;
            nvmeof_targets: components["schemas"]["NvmeofTargetInfo"][];
            pvc_info?: null | components["schemas"]["PvcInfo"];
            raid_status?: null | components["schemas"]["DashboardRaidStatus"];
            /** Format: double */
            rebuild_progress?: number | null;
            replica_statuses: components["schemas"]["DashboardReplicaStatus"][];
            /** Format: int32 */
            replicas: number;
            size: string;
            spdk_validation_status: components["schemas"]["SpdkValidationStatus"];
            state: string;
            /** Format: int32 */
            target_port: number;
            transport_type: string;
            ublk_device?: Record<string, never> | null;
        };
        DeleteDiskRequest: {
            pci_address: string;
        };
        DeleteVolumeSnapshotResponse: {
            content?: string | null;
            error?: string | null;
            name: string;
            namespace: string;
            success: boolean;
        };
        /**
         * @description Outcome of deleting a disk's LVS (the inverse of setup/initialize).
         *     A refusal while lvols still exist comes back as 409 with the reason in
         *     `error`; deleting an uninitialized disk is a successful no-op.
         */
        DiskDeleteResponse: {
            completed_at: string;
            error?: string | null;
            message?: string | null;
            success: boolean;
        };
        DiskSetupRequest: {
            backup_data?: boolean | null;
            disks?: string[] | null;
            force_unmount?: boolean | null;
            pci_addresses?: string[] | null;
        };
        /**
         * @description Per-disk outcome shape for setup/initialize/reset. `failed_disks` holds
         *     PCI addresses only — human-readable causes ride in `warnings`.
         */
        DiskSetupResponse: {
            completed_at: string;
            failed_disks: string[];
            setup_disks: string[];
            success: boolean;
            warnings: string[];
        };
        DisksResponse: {
            disks: components["schemas"]["DashboardDisk"][];
            node_info: {
                [key: string]: components["schemas"]["NodeInfo"];
            };
            nodes: string[];
        };
        EventsResponse: {
            events: components["schemas"]["DashboardEvent"][];
            windows: components["schemas"]["HotRejoinWindow"][];
        };
        /**
         * @description A completed hot-rejoin window parsed from a HotRejoinSucceeded event —
         *     the after-the-fact record of the sub-2s window the 2a indicator cannot
         *     catch live.
         */
        HotRejoinWindow: {
            epoch: string;
            /** Format: int64 */
            estimator_bytes?: number | null;
            node: string;
            path: string;
            raid: string;
            steps: components["schemas"]["WindowStep"][];
            timestamp?: string | null;
            volume: string;
            /** Format: int64 */
            window_ms: number;
        };
        LoginRequest: {
            password: string;
            username: string;
        };
        LoginResponse: {
            /** Format: int64 */
            expires_in_secs: number;
            role: components["schemas"]["Role"];
            token: string;
        };
        /**
         * @description Agent-level failure envelope (also produced by the dashboard proxy when
         *     an agent is unreachable).
         */
        NodeAgentError: {
            error: string;
            success: boolean;
        };
        /**
         * @description Disk row served by POST /api/disks/uninitialized — same compatibility
         *     shape minus the status-only telemetry fields.
         */
        NodeDiskListing: {
            blobstore_initialized: boolean;
            device_id: string;
            device_name: string;
            discovered_at: string;
            driver: string;
            driver_ready: boolean;
            filesystem_type?: string | null;
            firmware_version: string;
            healthy: boolean;
            is_system_disk: boolean;
            model: string;
            mounted_partitions: string[];
            /** Format: int32 */
            namespace_id: number;
            /** Format: int32 */
            numa_node: number;
            pci_address: string;
            serial: string;
            /** Format: int64 */
            size_bytes: number;
            spdk_ready: boolean;
            subsystem_device_id: string;
            subsystem_vendor_id: string;
            vendor_id: string;
        };
        /**
         * @description Disk row served by POST /api/disks/status — the Disk Setup tab's source.
         *     Several fields are fixed compatibility values the agent fabricates for the
         *     frontend (vendor ids, empty serial, numa 0); typed here so the generated
         *     OpenAPI spec documents what is actually sent.
         */
        NodeDiskStatus: {
            blobstore_initialized: boolean;
            device_id: string;
            device_name: string;
            discovered_at: string;
            driver: string;
            driver_ready: boolean;
            /** Format: int64 */
            error_count: number;
            filesystem_type?: string | null;
            firmware_version: string;
            /** Format: int64 */
            free_space: number;
            healthy: boolean;
            is_system_disk: boolean;
            model: string;
            mounted_partitions: string[];
            /** Format: int32 */
            namespace_id: number;
            /** Format: int32 */
            numa_node: number;
            pci_address: string;
            serial: string;
            /** Format: int64 */
            size_bytes: number;
            spdk_ready: boolean;
            subsystem_device_id: string;
            subsystem_vendor_id: string;
            /** Format: double */
            temperature?: number | null;
            vendor_id: string;
        };
        NodeDisksStatusResponse: {
            disks: components["schemas"]["NodeDiskStatus"][];
            last_updated: string;
            node: string;
        };
        NodeInfo: {
            /** Format: int64 */
            memory_available_mb: number;
            /** Format: int64 */
            memory_total_mb: number;
            /** Format: int64 */
            memory_used_mb: number;
            /** Format: double */
            memory_utilization_pct: number;
            name: string;
        };
        /**
         * @description Per-node fleet rollup — the nodes tab's landing payload. Grows with
         *     node count only, never with per-volume/per-disk detail (that stays in
         *     the aggregate, fetched when one node is drilled into).
         */
        NodeSummary: {
            /** Format: double */
            allocated_gb: number;
            /** Format: double */
            capacity_gb: number;
            /** Format: int32 */
            disks_healthy: number;
            /** Format: int32 */
            disks_total: number;
            /**
             * Format: int32
             * @description Non-system disks with no blobstore — init candidates (onboarding
             *     work, not a health condition).
             */
            disks_uninitialized: number;
            /**
             * @description Worst condition on the node: "critical" | "warning" | "ok".
             *     critical = unhealthy disk or failed volume/replica here;
             *     warning = degraded volume or out-of-sync replica here.
             */
            health: string;
            /** Format: int32 */
            local_nvme_volumes: number;
            name: string;
            /**
             * Format: int32
             * @description This node's replicas not in_sync (stale/standby/rejoining).
             */
            replicas_out_of_sync: number;
            /**
             * Format: int32
             * @description Volumes with a replica here whose state is not Healthy.
             */
            volumes_not_healthy: number;
            /**
             * Format: int32
             * @description Volumes with a replica on this node.
             */
            volumes_total: number;
        };
        NodesResponse: {
            nodes: components["schemas"]["NodeSummary"][];
        };
        NvmeofTargetInfo: {
            active: boolean;
            bdev_name: string;
            /** Format: int64 */
            connection_count: number;
            node: string;
            nqn: string;
            target_ip: string;
            /** Format: int32 */
            target_port: number;
            transport: string;
        };
        NvmfTarget: {
            nqn: string;
            target_ip: string;
            target_port: string;
            transport_type: string;
        };
        OrphanedVolumeInfo: {
            orphaned_since: string;
            /** Format: int64 */
            size_blocks: number;
            /** Format: double */
            size_gb: number;
            spdk_volume_name: string;
            spdk_volume_uuid: string;
        };
        ProvisionedVolume: {
            provisioned_at: string;
            replica_type: string;
            /** Format: int64 */
            size: number;
            status: string;
            volume_id: string;
            volume_name: string;
        };
        PvcInfo: {
            creation_timestamp: string;
            name: string;
            namespace: string;
            storage_class: string;
        };
        RaidMember: {
            name: string;
            /** Format: int32 */
            slot: number;
            state: string;
            uuid?: string | null;
        };
        RebuildInfo: {
            /** Format: int64 */
            blocks_remaining: number;
            /** Format: int64 */
            blocks_total: number;
            estimated_time_remaining?: string | null;
            /** Format: double */
            progress_percentage: number;
            /** Format: int32 */
            source_slot: number;
            start_time?: string | null;
            state: string;
            /** Format: int32 */
            target_slot: number;
        };
        RefreshResponse: {
            error?: string | null;
            message?: string | null;
            status: string;
        };
        /**
         * @description Per-replica sync state projected from the PV `replica-sync-state`
         *     annotation — the Tier-2 engine's live signal. `rebuild_progress` above
         *     tracks the pre-Tier-2 blind-rebuild model and stays for raid-level
         *     rebuild_info only; replica health is judged from here.
         */
        ReplicaSyncInfo: {
            /** Format: int64 */
            epoch_lag?: number | null;
            hot_rejoin?: string | null;
            last_epoch?: string | null;
            reason?: string | null;
            since?: string | null;
            sync_state: string;
        };
        /**
         * @description Ordering matters: authorization checks are `role >= minimum`.
         * @enum {string}
         */
        Role: "viewer" | "admin";
        /**
         * @description Get all snapshots from all nodes
         *     One node's copy of a logical snapshot (same shape as the tree
         *     endpoint's replica_bdev_details entries, which the snapshots tab
         *     already renders).
         */
        SnapshotCopy: {
            aliases: string[];
            driver: string;
            /** @description SPDK lvol snapshot name on that node. */
            name: string;
            node: string;
            snapshot_source_bdev: string;
        };
        SnapshotTimelineEvent: {
            /** @description RFC3339. None only for orphans (no CR, and SPDK stores no time). */
            created_at?: string | null;
            /** Format: int64 */
            epoch_seq?: number | null;
            /**
             * @description Stable identity: VolumeSnapshotContent name for user snapshots,
             *     epoch snapshot name for epochs, SPDK lvol name for orphans.
             */
            id: string;
            /** @description "user" (VolumeSnapshot-backed) or "epoch" (engine-cut). */
            kind: string;
            /** @description Display name: the VolumeSnapshot name, or the epoch/lvol name. */
            name: string;
            /** @description Nodes whose SPDK currently holds a copy of this snapshot. */
            nodes: string[];
            /**
             * @description SPDK-side user snapshot with no VolumeSnapshot CR behind it
             *     (Retain-policy leftovers). Not deletable through the CR path.
             */
            orphan: boolean;
            ready: boolean;
            /** Format: int64 */
            size_bytes?: number | null;
            /** @description SPDK lvol snapshot name (the CSI snapshot handle), when known. */
            spdk_name?: string | null;
            vs_name?: string | null;
            vs_namespace?: string | null;
            vsc_name?: string | null;
        };
        SnapshotTimelineResponse: {
            current_epoch?: string | null;
            /** @description Chronological (unknown-time orphans last). */
            events: components["schemas"]["SnapshotTimelineEvent"][];
            /** @description Server time at response build — the frontend's "now" anchor. */
            now: string;
            replicas: components["schemas"]["TimelineReplica"][];
            /**
             * Format: int64
             * @description SPDK epoch snapshots not (or no longer) in the PV's retained-epoch
             *     record — mid-rotation stragglers. Counted, never plotted at a
             *     fabricated position.
             */
            untracked_epochs: number;
            volume_id: string;
        };
        SpdkValidationStatus: {
            has_spdk_backing: boolean;
            validation_message?: string | null;
            validation_severity: string;
        };
        TimelineReplica: {
            last_epoch?: string | null;
            node: string;
            sync_state: string;
        };
        UninitializedDisksResponse: {
            count: number;
            node: string;
            success: boolean;
            uninitialized_disks: components["schemas"]["NodeDiskListing"][];
        };
        VolumesResponse: {
            raw_volumes: Record<string, never>[];
            volumes: components["schemas"]["DashboardVolume"][];
        };
        WindowStep: {
            /** Format: int64 */
            ms: number;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard: {
        parameters: {
            query?: {
                volume_filter?: string;
                volume_node?: string;
                disk_node?: string;
                disk_initialized?: boolean;
                nodes_with_disks_only?: boolean;
                node?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full aggregate (uncached legacy endpoint) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardData"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Aggregate build failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    disks: {
        parameters: {
            query?: {
                volume_filter?: string;
                volume_node?: string;
                disk_node?: string;
                disk_initialized?: boolean;
                nodes_with_disks_only?: boolean;
                node?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disks slice of the cached aggregate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisksResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Aggregate build failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: {
                volume?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engine event timeline + parsed hot-rejoin windows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Event list failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    nodes_projection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-node fleet rollup (health, disk/volume/sync counts) from the cached aggregate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodesResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Aggregate build failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    node_disks_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kubernetes node name */
                node: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteDiskRequest"];
            };
        };
        responses: {
            /** @description LVS deleted (or no-op on an uninitialized disk) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskDeleteResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Viewer token on a destructive route */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Refused: logical volumes still exist on the LVS */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskDeleteResponse"];
                };
            };
            /** @description Agent unreachable or SPDK error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskDeleteResponse"];
                };
            };
        };
    };
    node_disks_initialize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kubernetes node name */
                node: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiskSetupRequest"];
            };
        };
        responses: {
            /** @description Alias of /disks/setup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskSetupResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Viewer token on a destructive route */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Agent unreachable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeAgentError"];
                };
            };
        };
    };
    node_disks_reset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kubernetes node name */
                node: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiskSetupRequest"];
            };
        };
        responses: {
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Viewer token on a destructive route */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Reset not implemented in minimal state */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskSetupResponse"];
                };
            };
        };
    };
    node_disks_setup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kubernetes node name */
                node: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiskSetupRequest"];
            };
        };
        responses: {
            /** @description Per-disk outcomes; idempotent on initialized disks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiskSetupResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Viewer token on a destructive route */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Agent unreachable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeAgentError"];
                };
            };
        };
    };
    node_disk_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kubernetes node name */
                node: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All healthy disks on the node (Disk Setup tab source) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDisksStatusResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Agent unreachable or discovery failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeAgentError"];
                };
            };
        };
    };
    node_disks_uninitialized: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Kubernetes node name */
                node: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All healthy disks (field name is historical) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UninitializedDisksResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Agent unreachable or discovery failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeAgentError"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverview"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Aggregate build failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache invalidated; agents rediscovered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    snapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logical snapshots: per-node SPDK copies merged by snapshot name, one replica_bdev_details entry per copy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSnapshot"][];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    snapshots_timeline: {
        parameters: {
            query: {
                volume: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-volume snapshot timeline: user VolumeSnapshots (real CR creation times) merged with engine epochs (PV-annotation recorded_at) and SPDK per-node presence */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotTimelineResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    volumes: {
        parameters: {
            query?: {
                volume_filter?: string;
                volume_node?: string;
                disk_node?: string;
                disk_initialized?: boolean;
                nodes_with_disks_only?: boolean;
                node?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Volumes slice of the cached aggregate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumesResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Aggregate build failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    volumesnapshot_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description VolumeSnapshot namespace */
                namespace: string;
                /** @description VolumeSnapshot name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VolumeSnapshot CR deleted; snapshot-controller retires the content/SPDK data per deletionPolicy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteVolumeSnapshotResponse"];
                };
            };
            /** @description Missing/expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Viewer token on a destructive route */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such VolumeSnapshot */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteVolumeSnapshotResponse"];
                };
            };
            /** @description Refused: snapshot belongs to a different CSI driver */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteVolumeSnapshotResponse"];
                };
            };
            /** @description Kubernetes API failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteVolumeSnapshotResponse"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness probe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
